# --Build stage--
FROM eclipse-temurin:25-jdk AS build

# Install maven manually in case CI/CD base imaage does't include itRUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/list/*

# Set working directory
WORKDIR /app

# Copy pom.xml fist for dependency caching
COPY pom.xml .

# Download dependencies
RUN mvn -B dependency:go-offline

# Copy source code
COPY src ./src

# Build the application (skip tests for faster build)
RUN mvn -B clean package -DskipTests


#----Runtime stage---
FROM eclipse-temurin:25-jre

# Set working directory
WORKDIR /app

# Copy the built jar from the build stage
COPY --from=build /app/target/*.jar app.jar

# Expose the application port
EXPOSE 8080

# Run the spring boot application
ENTRYPOINT ["java", "-jar", "app.jar"]

