spring.application.name=Spring-AI-Workshop

server.port=8080

# set open API key
spring.ai.openai.api-key=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
# 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
